version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend:/app
    working_dir: /app
    env_file:
      - .env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    command: npm run dev --host=0.0.0.0
    restart: always
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend