# Generated by Django 5.1.4 on 2025-01-05 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('iglesia', models.CharField(max_length=40)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fechaDesde', models.DateField(default=datetime.datetime(2025, 1, 5, 22, 47, 36, 574390, tzinfo=datetime.timezone.utc))),
                ('fechaHasta', models.DateField(default=datetime.datetime(2025, 1, 5, 22, 47, 36, 574390, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
